#
# Module manifest for module 'ViewSonic.myViewBoard'
#
# Generated by: ColtonKenney
#
# Generated on: 3/31/2026
#

@{

    # Script module or binary module file associated with this manifest.
    RootModule           = "ViewSonic.myViewBoard.psm1"

    # Version number of this module.
    ModuleVersion        = "1.1.1"

    # Supported PSEditions
    CompatiblePSEditions = @("Desktop", "Core")

    # ID used to uniquely identify this module
    GUID                 = "4D199785-AA73-4292-BE29-480854964B6D"

    # Author of this module
    Author               = "Apocrypher00"

    # Company or vendor of this module
    CompanyName          = "Community"

    # Copyright statement for this module
    Copyright            = "This is free and unencumbered software released into the public domain."

    # Description of the functionality provided by this module
    Description          = "PowerShell module for ViewSonic myViewboard REST API"

    # Minimum version of the PowerShell engine required by this module
    PowerShellVersion    = "5.1"

    # Name of the PowerShell host required by this module
    # PowerShellHostName = ""

    # Minimum version of the PowerShell host required by this module
    # PowerShellHostVersion = ""

    # Minimum version of Microsoft .NET Framework required by this module.
    # This prerequisite is valid for the PowerShell Desktop edition only.
    # DotNetFrameworkVersion = ""

    # Minimum version of the common language runtime (CLR) required by this module.
    # This prerequisite is valid for the PowerShell Desktop edition only.
    # ClrVersion = ""

    # Processor architecture (None, X86, Amd64) required by this module
    # ProcessorArchitecture = ""

    # Modules that must be imported into the global environment prior to importing this module
    # RequiredModules = @()

    # Assemblies that must be loaded prior to importing this module
    # RequiredAssemblies = @()

    # Script files (.ps1) that are run in the caller's environment prior to importing this module.
    # ScriptsToProcess = @()

    # Type files (.ps1xml) to be loaded when importing this module
    TypesToProcess       = @(
        "Types\DeviceProfile.Types.ps1xml"
        "Types\DeviceStatistics.Types.ps1xml"
        "Types\DeviceUsage.Types.ps1xml"
        "Types\GroupDeviceInfo.Types.ps1xml"
        "Types\GroupInfo.Types.ps1xml"
        "Types\Media.Types.ps1xml"
        "Types\Playlist.Types.ps1xml"
    )

    # Format files (.ps1xml) to be loaded when importing this module
    FormatsToProcess     = @(
        "Formats\DeviceProfile.Format.ps1xml"
        "Formats\DeviceStatistics.Format.ps1xml"
        "Formats\DeviceUsage.Format.ps1xml"
        "Formats\GroupDevice.Format.ps1xml"
        "Formats\GroupInfo.Format.ps1xml"
    )

    # Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
    # NestedModules = @()

    # Functions to export from this module, for best performance,
    # do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
    FunctionsToExport    = @(
        "Get-Device"
        "Get-DeviceStatistics"
        "Get-DeviceUsage"
        "Get-Group"
        "Get-GroupDevice"
        "Get-Media"
        "Get-Playlist"
        "Get-Resource"
        "Invoke-Method"
        "Set-Config"
    )

    # Cmdlets to export from this module, for best performance,
    # do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
    CmdletsToExport      = @()

    # Variables to export from this module
    VariablesToExport    = @()

    # Aliases to export from this module, for best performance,
    # do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
    AliasesToExport      = @()

    # DSC resources to export from this module
    # DscResourcesToExport = @()

    # List of all modules packaged with this module
    # ModuleList = @()

    # List of all files packaged with this module
    # FileList = @()

    # Private data to pass to the module specified in RootModule/ModuleToProcess.
    # This may also contain a PSData hashtable with additional module metadata used by PowerShell.
    PrivateData          = @{

        PSData = @{

            # Tags applied to this module. These help with module discovery in online galleries.
            Tags                     = @("ViewSonic", "myViewBoard", "REST", "API")

            # A URL to the license for this module.
            LicenseUri               = "https://github.com/Apocrypher00/ViewSonic.myViewBoard/blob/master/LICENSE"

            # A URL to the main website for this project.
            ProjectUri               = "https://github.com/Apocrypher00/ViewSonic.myViewBoard"

            # A URL to an icon representing this module.
            # IconUri                  = "https://myviewboard.com/mydashboard/dm/favicon.svg"

            # ReleaseNotes of this module
            ReleaseNotes             = @'
Fixes import issues introduced in 1.1.0.

Changes:
- Fixed Invoke-Method parameter validation so the module imports correctly
- Fixed format and type ps1xml compatibility for Windows PowerShell 5.1
'@

            # Prerelease string of this module
            # Prerelease = ""

            # Flag to indicate whether the module requires explicit user acceptance for install/update/save
            RequireLicenseAcceptance = $false

            # External dependent modules of this module
            # ExternalModuleDependencies = @()

        } # End of PSData hashtable

    } # End of PrivateData hashtable

    # HelpInfo URI of this module
    # HelpInfoURI = ""

    # Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
    DefaultCommandPrefix = "MVB"
}

